sudo: false
language: node_js
node_js: '0.12'
script:
- travis-lint .travis.yml
- make jscs
- make jshint
- npm test
- make codeclimate
- make check-if-built
cache:
  directories:
  - node_modules
env:
  global:
    secure: "gM/AISWQVs+/Y7ClL5fYmVKIdw80mgQC5GL7O+kunkQEG6yT5rQIaCE5FpTQZhPqby5qCVzAMdVMImDtZSpEfyursmOQJRuPZrp/4PeqlSxj4dPCvuVBsfc+mDzgASXUynljJXrKpvD3/hSQLf+KU+S8y57kXeGOOnTPee4g2KMu5yB8Ap1IVLDvE0PgGgQ+gRLauPRTZoxn2rRWkr1UNVFODNWxw/nuqzWnfLH8BG4Wje0rHo1UqzWQr9MQB3JD82nDzJj3xc6CBEkeQoLuqZUPT066bTp2C+V7cubCoy5FcOs8+yKLhGDcO2/iHZfE1SJ4LeqdtaZVEfepU3ZiT131lT3WF4rNGjIi5MdJxPkHBP3R4+LkQ5HNNUd36pUucyB+/tjN8PQFQipi+v29DvHwFdwDB2QzrLopy3safeyg/A+RacYUFrHoCbYBscSx9NePkRkG6Bgn95gPBwQFUIQGQIN51Z//gSEDwO1+tTR4zKPV2jn5rZE2Lz/BD8N8mekTTA6hct95L1o0mH022yeeIhf1VF23V+PhNzY1vnaxg/O6oI3ejpOS2QTrNl++1qWgiVZ1u2ociM7vTTBdRtmmIK3IBJ4M0E3AmExjOqegF9+Hf4+PKfxdWSASfdfexAyWWc4dKOEufF5tkZDKNP6mVlhpWpa5J9UkC2xoCJM="
